---

- include_vars: roles/LB/vars/backends.yaml
- include_vars: roles/LB/vars/root_pass.yml

- name: Iptables config deploy
  copy: src=iptables/iptables.rules dest=/etc/iptables.rules
  notify: Iptables reload

- name: HaProxy install
  package: pkg=haproxy state=installed

- name: 'Create directory for custom frontend'
  file:
    path: "/etc/haproxy/backends.d"
    state: directory

- name: Build up the backetnd
  template:
    src: "backend.cfg"
    dest: "/etc/haproxy/backends.d/{{ item.name }}.cfg"
  with_items: "{{ haproxy_backends }}"
  when: haproxy_backends is defined

- name: Haproxy default config deploy
  copy: src=haproxy.cfg dest=/etc/haproxy/backends.d/haproxy.cfg_dist

- name: Build Main Configuration file
  assemble:
    src: "/etc/haproxy/backends.d"
    dest: "/etc/haproxy/haproxy.cfg"
    backup: yes
    validate: "haproxy -c -f %s"
  notify: haproxy reload

- name: Additional App install
  package: pkg={{ item }} state=installed 
  with_items:
    - ca-certificates
    - vim
    - wget
    - curl
    - git
    - rsync
