#jinja2: lstrip_blocks:True, trim_blocks:True
FROM alpine

RUN apk --no-cache add nginx

RUN rm -rf /etc/nginx/*
RUN rm -rf /usr/share/nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY releases/{{release_tag}}/* /var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

