---

repo_url: https://github.com/roylines/docker-nginx
release_tag: master

jenkins_server: localhost

project_name: test_web
registry_url: pgd988

### SWARM service param:
service_port_published: 8080
service_port_target: 80
reprl_def_count: 5
rollback_parallelism: 2
rollback_monitor: 20s
rollback_max_failure_ratio: 2
########################
